Zylann/godot_voxel

- streams/voxel_stream.cpp
- voxel.cpp
Fixes two small bugs:
1. Voxel_name bindings were incorrect, which meant you couldn't read/write the variable like `print(voxel.voxel_name)`.
2. Calling emerge used the wrong overloaded version and resulted in a returned error, thus the call never got to the script.
fixes #30
> Emerge bugfix

- terrain/voxel_terrain.cpp
Currently VoxelTerrain doesn't bind set_material, so you can't set a material from code like you can with  VoxelLodTerrain. This PR adds the bindings.
> Allow VoxelTerrain.set_material() from gdscript

- streams/voxel_stream_noise.cpp
- streams/voxel_stream_noise.h
- terrain/voxel_terrain.cpp
Adds 3D noise functionality to blocky voxel terrain.
This PR includes the previous one which fixes voxel terrain visibility. I'm not sure if it will automatically go away when you merge, or if I need to pull it out of the PR.
Fixes #80
> Enables 3D Noise on Blocky VoxelTerrain

- edition/voxel_tool_terrain.cpp
Not sure if this is the right way of fixing this, but I have some transparent blocks like glass or leaves that I still want to place other blocks onto, but the raycast method ignored them. This is my quick, but there might be better solution like maybe having some sort of raycast option in the VoxelLibrary.
Closes issue #153
> Fixed cannot place blocks on transparent blocks

- editor/graph/voxel_graph_editor.cpp
- generators/graph/voxel_generator_graph.cpp
- generators/graph/voxel_graph_node_db.h
- meshers/blocky/voxel.cpp
Not sure how useful this is, but it does fix the `Wreorder`, `Wsign-compare`, and `Wparentheses` warnings that were shown while compiling (gcc). If useful, will squash before before merge. 
EDIT: there was similar previous PR: https://github.com/Zylann/godot_voxel/pull/120, as well as couple others
> Fix warnings

- meshers/blocky/voxel.cpp
In order to build godot with godot_voxel and mono I had to make the change to the is_empty binding in meshers/blocky/voxel.cpp
Without this change the cs file generated during `./bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue` is not valid C# code.
I'm not sure if this will cause or fix a similar problem creating other bindings -- for gdscript for instance.
This is my first contribution to anything godot related, so this change is more of an educated guess than anything :)
> Fix binding of is_empty to allow build with mono

- meshers/blocky/voxel.cpp
- meshers/blocky/voxel.h
I had to make a few changes to the latest version so that I could run
`./bin/godot.x11.opt.tools.64.mono --generate-mono-glue modules/mono/glue`
to generate the C# bindings.
Without these changes the command exits with:
```
Generating Voxel.cs...
ERROR: _generate_cs_property: Condition "getter->return_type.cname != setter->arguments.back()->get().type.cname" is true. Returned: ERR_BUG
At: modules/mono/editor/bindings_generator.cpp:1428.
ERROR: _generate_cs_type: Failed to generate property 'transparency_index' for class 'Voxel'.
At: modules/mono/editor/bindings_generator.cpp:1298.
ERROR: generate_cs_api: Generation of the Core API C# project failed.
At: modules/mono/editor/bindings_generator.cpp:1114.
ERROR: handle_cmdline_args: --generate-mono-glue: Failed to generate the C# API.
At: …
```
> Fix bindings so that generate-mono-glue for C# bindings works

- storage/voxel_buffer.cpp
Fix dead loop in 'VoxelBuffer::for_each_voxel_metadata_in_area' and 'VoxelBuffer::clear_voxel_metadata_in_area'
> Fix dead loop in VoxelBuffer

- generators/graph/range_utility.cpp
Comparing the bitwise 'and' result and a number inside the if in this way results always false unless the bitwise 'and' result is 1.
If the intended use of the variable `tests` is as bitflags, then it's wrong to compare the different results to the same integer number since the bitwise & operation can return at most 0 or the bitmask. This triggered a compiler error when compiled with -werror=yes (and curiously this was not triggered in the CI despite the compile command including that flag)
> Fix tautological-compare error

- terrain/voxel_lod_terrain.cpp
Attempts to fix #237
Fixes a bug in calculation of bounds for neighbor check.
> bug fix in voxel_lod_terrain.cpp

- terrain/instancing/voxel_instance_generator.cpp
The instance generator was using the y position relative to the block when checking if the instance is within the min_height and max_height range. I fixed it by having use the y position relative to the terrain for filtering instead.
> Fix instance generator using wrong height for filtering

- doc/classes/VoxelInstanceLibraryItem.xml
- terrain/instancing/voxel_instance_library_item.cpp
- terrain/instancing/voxel_instance_library_item.h
- terrain/instancing/voxel_instancer.cpp
- util/godot/direct_multimesh_instance.cpp
- util/godot/direct_multimesh_instance.h
This adds the cast_shadow property to DirectMultiMeshInstance and VoxelInstanceLibraryItem. This allows for instance items to have their shadow mode set from the editor but you still need to regenerate the terrain to see the difference.
> Added shadow mode setting to VoxelInstanceLibraryItems

- .github/workflows/mono.yml
This resolves #244 
I added Mono builds for Linux and Windows as a third github actions workflow. 
This works by generating the Mono glue in the first step and then sharing that glue with the Linux and 
Windows steps. This dependency is why I split it off into its own workflow because the alternative would generate the glue twice.
> Added Mono builds in a new Github Actions workflow

- .github/workflows/mono.yml
- nuget.config
This seems to be a problem with the Windows images being used to build.
More information in this thread: https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782
> Trying to fix Github build pipeline

- editor/vox/vox_mesh_importer.cpp
- storage/voxel_memory_pool.h
- streams/vox_data.cpp
This fixes errors I hit building master on macos 11.5.2 with clang 12.0.5, all concerning `size_t` type conversion.
> Fixed macos/clang build errors

- editor/voxel_debug.cpp
- terrain/instancing/voxel_instancer.cpp
- terrain/voxel_mesh_block.cpp
- util/godot/direct_mesh_instance.cpp
- util/godot/direct_mesh_instance.h
- util/godot/direct_multimesh_instance.cpp
- util/godot/direct_multimesh_instance.h
Use GLOBAL mode for direct_mesh_instance/direct_multimesh_instance
so that they are visible but not culled.
> Change portal culling mode for meshes/multimeshes

- storage/voxel_metadata_variant.cpp
- streams/voxel_block_serializer.cpp
Fixes https://github.com/Zylann/godot_voxel/issues/372
Currently in the process of making sure it doesn't break any of the builds, which is why this is still a DRAFT.
- Non-Arm64 Mac Build works: `scons -j4 platform=osx CXX=clang++ osxcross_sdk=darwin20.4 warnings=all tools=yes tests=no target=release_debug production=yes`
- (I removed the `werror=yes` for now, since Mac is not explicitly supported)
- Arm64 Mac Build doesn't work yet because of some fast_noise issues: `scons -j4 platform=osx CXX=clang++ osxcross_sdk=darwin20.4 arch=arm64 warnings=all tools=yes tests=no target=release_debug production=yes`
- It was related to #366 :
- The command I'm currently trying is `scons -j4 voxel_fast_noise_2=false platform=osx CXX=clang++ osxcross_sdk=darwin20.4 arch=arm64 warnings=all tools=yes …
> MacOS build: Fix size discrepancy between size_t and uint64_t in voxel_block_serializer.cpp

- util/span.h
On my machine (ubuntu 22.04) I was unable to compile the project.
First I was thinking I have some problem with matching proper godot engine version with proper voxel commit (especially that I had no problem with building 3.x version), but then I realized automatic builds are working here so I took the exact commits from two repos and I still had build errors, that made me look more closely at errors and I realized that most probably some of my system libraries were build in a bit different way and do not include some of the imports. 
After adding those everything builds nicely on current masters (godot 943b50995292d98d9bc2e45ff04eaf0a716cea28) (voxel module 668fedfa528f9971577f7bf19041f948db512d3d)
> Missing imports

- doc/source/getting_the_module.md
When the latest godot commit and the latest godot_voxel commit don't match, look at the latest successful Github action.
Also the godot_voxel/master is targeting the tip of the godot/master, so with breaking changes, a recent voxel/master commit won't work with all recent godot/master commits.
Still a first draft of what could be said, I'll try sleeping on it to come up with something clearer or at a better place in the doc
> DOC: Make it clearer where to look on building mismatch

- streams/region/region_file.cpp
gcc warns:
```
modules/voxel/streams/region/region_file.cpp: In function 'bool save_header(FileAccess*, uint8_t, const VoxelRegionFormat&, const std::vector<VoxelRegionBlockInfo>&)':
832
modules/voxel/streams/region/region_file.cpp:101:9: error: unused variable 'blocks_begin_offset' [-Werror=unused-variable]
833
101 |  size_t blocks_begin_offset = f->get_position();
const size_t blocks_begin_offset = f.get_position();
```
I noticed this while trying to build export templates using github
actions, as the godot actions treat warnings as errors by default:
https://github.com/rcorre/godot/runs/6617207436
> Avoid unused variable warning.

- server/voxel_server.cpp
Compiling for mac fails with:
```
clang++ -o modules/voxel/server/voxel_server.osx.opt.64.o -c -std=gnu++14 -Wno-inconsistent-missing-override -msse2 -O3 -fomit-frame-pointer -ftree-vectorize -arch x86_64 -mmacosx-version-min=10.12 -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -w -DNO_EDITOR_SPLASH -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGL_SILENCE_DEPRECATION -DNDEBUG -DPTRCALL_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMESHOPTIMIZER_ZYLANN_NEVER_COLLAPSE_BORDERS -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. modules/voxel/server/voxel_server.cpp
869 …
```
> Fix mac compilation on 3.x.

- .github/workflows/test_project.yml
Related to issue #397:
- Use the updated URL (I used the URL to which the old URL redirects).
- Use the updated project name (since an invalid source in `mv` command was causing a test to fail on all commits).
This PR only fixes the godot3.x branch.
- This one downloads the 3.x branch of the regression test project, so it differs from my PR for the master branch.
- Let me know: Are both this and that PR fine, or how are you approaching the master branch?
> Use the new project name and avoid a URL redirect (Fix #397).

- .github/workflows/test_project.yml
Related to issue #397:
- Use the updated URL (I used the URL to which the old URL redirects).
- Use the updated project name (since an invalid source in `mv` command was causing a test to fail on all commits).
This PR only fixes master (I will also look at 3.x branch and add another PR as necessary).
> Use the new project name and avoid a URL redirect.

- .gitignore
When compiling, I got temporary files showing up in my Git client with the extension `.tmp`. This PR ignores them. I also alphabetized the list so it's easy to find things.
> Add `*.tmp` to the .gitignore

- README.md
Looks like they were broken with a recent image optimization.
> Update broken image links in README

- edition/voxel_tool_lod_terrain.cpp
This is necessary after https://github.com/godotengine/godot/pull/57698 was merged into the engine.
> Rename translated to translated_local

- terrain/instancing/voxel_instance_generator.cpp
I checked the other renames as well, this was the only one.
> `deg2rad` was renamed in Godot (godotengine/godot#64367)

- .github/workflows/linux.yml
- .github/workflows/mono.yml
- .github/workflows/windows.yml
- doc/source/module_development.md
- doc/tools/build.py
- storage/funcs.cpp
- storage/voxel_buffer_internal.cpp
- util/godot/string.h
* Fixes to includes to make CI builds not compile with errors.
* Fix `find_godot` function in `doc/tools/build.py` and add support for macOS and other architectures (I didn't check if the whole script works but I did check that this specific file name logic and the regex is correct).
* Remove commented-out unit test running code in the workflows (the TODO comment was confusing and the file path is no longer correct, so remove and they can just be added back later if needed).
> Misc fixes to includes and build system

- engine/gpu_storage_buffer_pool.cpp
The return type of `pool.buffers.size()` has an ambiguous conversion to Variant, at least on Clang on macOS (since the CI succeeds for Windows and Linux I guess this may be a Clang or Mac specific issue).
This PR explicitly converts them to `int64_t` before using them in the Variant array. I used `int64_t` because that's the type Variant stores internally, so it's the least amount of casting, but the conversion would also work using `uint64_t` or `unsigned int` or any other type Variant is able to be constructed from.
> Fix compile error in GPU storage buffer pool debug print

- util/slot_map.h
When building on Linux the compiler complains about cstdint not being include, which results in types such uint32_t and other not being defined. 
In file included from modules/voxel/terrain/../engine/ids.h:4,
from modules/voxel/terrain/voxel_node.h:4,
from modules/voxel/terrain/voxel_node.cpp:1:
modules/voxel/terrain/../engine/../util/slot_map.h:13:22: error: 'uint32_t' does not name a type
13 |         static const uint32_t UNUSED_BIT = 1 << (8 * sizeof(TVersion) - 1);
|                      ^~~~~~~~
modules/voxel/terrain/../engine/../util/slot_map.h:7:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
6 | #include <vector>
+++ |+#include <cstdint>
This commit adds just that one line.
> Missing #include <cstdint> causes Linux build to fail.

- editor/graph/voxel_graph_editor.cpp
- util/godot/core/mouse_button.h
See https://github.com/godotengine/godot/pull/71045 for the engine and https://github.com/godotengine/godot-cpp/blob/master/gdextension/extension_api.json for GDExtension.
Should work in both the engine module and GDExtension but I only tested as an engine module.
> Fix compiling with Godot's MouseButton mask bitfield changes (beta 11)

- engine/save_block_data_task.cpp
stream.is_null()→stream.is_valid()
> Fix condition of ZN_ASSERT_RETURN_MSG:

- .github/workflows/mono.yml
Fixes #354
On Feb 7 in commit [da124e9d](https://github.com/godotengine/godot/commit/da124e9d04b2cd3d7be43f5653a6ffb2747a1c4a), Godot changed its apt sources and deleted `misc/ci/sources.list` from the repo, which broke the godot_voxel mono builds.
Update `mono.yml` to reflect these changes made in godot's CI: https://github.com/godotengine/godot/commit/da124e9d04b2cd3d7be43f5653a6ffb2747a1c4a
> Fix mono CI

- .github/workflows/mono.yml
Builds [the managed libraries via build_assemblies.py](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html#building-the-managed-libraries), which adds the `GodotSharp` directory, which fixes this error when starting the editor:
(The official release doesn't need the `GodotSharp` directory & files, but I think that's just because they packaged it into the executable with fancier build actions)
Mono is no longer installed on the `Windows Editor w/ Mono` image since the "windows-latest" base comes with dotnet 6.0, which Godot 4 has switched to.
----
* I've added the same `build_assemblies.py` change to the mono-linux build, it builds successfully but I haven't tested the binaries as I don't have a non-remote linux box.
* On Windows, the Godot …
> Fix "Failed to load .NET runtime" in mono CI builds

- .github/workflows/extension_windows.yml
- .github/workflows/linux.yml
- .github/workflows/mono.yml
- .github/workflows/windows.yml
The following updates are performed:
* update [`actions/cache`](https://github.com/actions/cache) to v3
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* update [`actions/download-artifact`](https://github.com/actions/download-artifact) to v3
* update [`actions/setup-python`](https://github.com/actions/setup-python) to v4
* update [`actions/upload-artifact`](https://github.com/actions/upload-artifact) to v3
Still using the outdated actions will generate several warnings in CI runs, for example in https://github.com/Zylann/godot_voxel/actions/runs/5204696634:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2, actions/setup-python@v2, actions/download-artifact@v2, …
> Update GitHub Actions CI

- thirdparty/lz4/LICENSE
- thirdparty/lz4/lz4.c
- thirdparty/lz4/lz4.h
Files are taken from <https://github.com/lz4/lz4/tree/v1.9.4/lib>, the official Git repository of lz4.
For a list of changes between versions 1.9.1 and 1.9.4 see <https://github.com/lz4/lz4/releases>.
> Update third-party library lz4 to version 1.9.4

- thirdparty/sqlite/sqlite3.h
- thirdparty/sqlite/sqlite3ext.h
- thirdparty/sqlite/version.md
Contains several fixes. For a full list see the official site: <https://sqlite.org/changes.html>
Files are taken from SQLite's source code amalgamation for version 3.42.0, https://sqlite.org/2023/sqlite-amalgamation-3420000.zip.
> Update third-party library SQLite to version 3.42.0

- meshers/blocky/voxel_blocky_model_mesh.cpp
On the current state, clang builds (required for macOS) will emit an unused variable warning.
`tangents_empty` isn't used outside of editor builds anyway.
This might make macOS checks (which use werror) work.
> Supress unused variable warning on VoxelBlockyModelMesh

- editor/fast_noise_2/chart_view.cpp
- editor/fast_noise_2/fast_noise_2_editor_plugin.h
- generators/simple/voxel_generator_noise_2d.cpp
- meshers/blocky/voxel_blocky_model_mesh.cpp
- meshers/transvoxel/transvoxel_cell_iterator.h
- util/slot_map.h
Fixes some warnings like `inconsistent-missing-override` and `unused-variable/function`.
I'm not sure if the changes on `slot_map.h` are valid. Just submitting because this is the change requested and it managed to compile successfully.
Follow up for #534.
This does not fix **ALL** of them. However, I can tell where the remaining are:
```
modules/voxel/storage/voxel_data.cpp:469:23: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
bbox.for_each_cell([this, &data_lod0, lod0_new_blocks_to_lod](Vector3i block_pos_lod0) {
^~~~~
modules/voxel/storage/voxel_data_map.cpp:68:14: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
map_block = std::move(VoxelDataBlock(buffer, _lod_index));
^
modules/voxel/storage/voxel_data_map.cpp:68:14: note: remove …
```
> Fix some clang complains

- meshers/blocky/types/voxel_blocky_type.cpp
The Minecraft Fandom wiki has been forked to a new domain: minecraft.wiki. Learn more here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates the old wiki link accordingly.
> Update Minecraft wiki link to new domain

- edition/voxel_tool_terrain.cpp
The `RaycastPredicteBlocky` did not actually check for model's `collision_aabbs`. Now I've made it do that.
> Make raycast based on model's collision_aabbs

- util/godot/classes/collision_shape_3d.h
- util/godot/classes/physics_body_3d.h
- util/godot/classes/rigid_body_3d.h
The title says it all, I've had problems building from source because the godot devs moved all physics related files to `scenes/3d/physics`.
> fix: fix broken builds because of godot physics files moved to another directory

- thirdparty/sqlite/VERSION.txt
- thirdparty/sqlite/sqlite3.h
- thirdparty/sqlite/sqlite3ext.h
For a full changelog see:
- https://sqlite.org/changes.html
(previously used version - 3.42.0)
---
Files are taken from SQLite's source code amalgamation for the version 3.45.2:
- https://sqlite.org/2024/sqlite-amalgamation-3450200.zip (2.61 MiB)
---
Additionally changed `thirdparty/sqlite/version.md` to `thirdparty/sqlite/VERSION.txt` (there is no need to store it as a Markdown file).
> SQLite: Update to 3.45.2

- doc/classes/VoxelTool.xml
- edition/voxel_tool.cpp
Changes:
- Fixed `grow_sphere` not using `sdf_scale` in its calculations.
- Increased allowed strength parameter range for `grow_sphere` from [0, 1] to [0, 10].
> Small grow_sphere adjustments

- meshers/blocky/types/voxel_blocky_type_library.cpp
The editor will crash if you try to save a scene with an empty VoxelBlockyType.
This PR fixes that by adding a null check.
> Fix crash when saving an empty VoxelBlockyType

- doc/classes/VoxelModifier.xml
- doc/classes/VoxelModifierMesh.xml
- doc/classes/VoxelModifierSphere.xml
Add documentation for VoxelModifier, VoxelModifierSphere and VoxelModifierMesh classes.
> Add documentation for VoxelModifier classes

- LICENSE.md
This pull request makes it, so that license type gets automatically detected. License fixed based on this comment: https://stackoverflow.com/a/75407346.
Also updated copyright year.
Before (current situation):
After (if this PR was merged):
> Make license type get auto detected

- .github/workflows/fuzzer.yml
- README.md
Fixed fuzzer issues:
- `System.IO.IOException: No space left on device`: fixed by adding `Free disk space` step before compilation step.
- Then there was an issue of step trying to fetch 4.2 version of `qarmin/Qarminer` repository, but only 4.1 exists there. I made an [issue](https://github.com/qarmin/Qarminer/issues/32) about it, but the author said that 4.1 version should work with Godot version up to 4.3+. So I hardcoded it to 4.1 for now. This may need to be updated later.
Fuzzer working and catching Godot crashes can be seen here:
<https://github.com/Piratux/godot_voxel/actions/runs/9821448650>
> Fix fuzzer

- edition/funcs.cpp
- generators/graph/node_type_db.cpp
- meshers/transvoxel/transvoxel.cpp
- streams/sqlite/connection.cpp
- streams/voxel_block_serializer.cpp
- terrain/instancing/voxel_instance_generator.cpp
- thirdparty/fast_noise_2/SConscript
- util/string/expression_parser.cpp
Assortment of tweaks to support the arguments `warnings=extra werror=yes dev_build=yes d3d12=yes` in an MSVC context
> Various MSVC compilation fixes

- util/godot/core/dictionary.h
I was getting this error while compiling GDExtension
```
In file included from generators/graph/voxel_generator_graph.h:7,
from generators/graph/voxel_generator_graph.cpp:1:
generators/graph/../../util/godot/core/dictionary.h: In function 'bool zylann::godot::try_get(const godot::Dictionary&, const godot::Variant&, T&)':
generators/graph/../../util/godot/core/dictionary.h:26:17: error: 'v' has incomplete type
26 |         Variant v = d.get(key, Variant());
|                 ^
In file included from generators/graph/../../util/godot/core/dictionary.h:7:
godot-cpp/gen/include/godot_cpp/variant/dictionary.hpp:43:7: note: forward declaration of 'class godot::Variant'
43 | class Variant;
|       ^~~~~~~
generators/graph/../../util/godot/core/dictionary.h:29:38: error: incomplete type …
```
> Fix GDExtension build error: incomplete type 'godot::Variant'

- doc/classes/VoxelEngine.xml
- engine/voxel_engine.cpp
- engine/voxel_engine.h
- engine/voxel_engine_gd.cpp
- engine/voxel_engine_gd.h
- util/tasks/threaded_task_runner.cpp
- util/tasks/threaded_task_runner.h
This PR exposes two new methods in the `VoxelEngine` singleton (the GDScript version of the class):
- `int get_thread_count()`:
Returns the number of currently used threads in the thread pool.
Implemented as a call chain:
```
zylann::voxel::godot::VoxelEngine.get_thread_count()
-> zylann::voxel::VoxelEngine.get_thread_count()
-> _general_thread_pool.get_thread_count()
```
- `void set_thread_count(int count)`:
Sets the number of threads to be used by the thread pool.
Also implemented as a call chain:
```
zylann::voxel::godot::VoxelEngine.set_thread_count(int count)
-> zylann::voxel::VoxelEngine.set_thread_count(int count)
-> _general_thread_pool.set_thread_count(int count)
```
The docs have been updated to include these two new methods.
This PR also includes a fix for how the …
> Allow to set thread count at runtime

- edition/funcs.cpp
Just a quick and easy fix to uniform blocks getting skipped by calls to `run_blocky_random_tick` despite them having a `VoxelBlockyModel` which is tickable. This probably must have reversed the entire process instead, so uniform blocks that were **not** set to tickable were actually called? Not sure, but now uniform blocks are random ticked as expected. Thanks to @Zylann!
> Fix uniform blocks getting skipped by `run_blocky_random_tick`

- thirdparty/sqlite/VERSION.txt
- thirdparty/sqlite/sqlite3.h
- thirdparty/sqlite/sqlite3ext.h
Just saw that the last SQLite update was over a year ago. Bumped to the latest SQLite version available at this time, **2025-07-30 (3.50.4)**, using the [sqlite-amalgamation-3500400.zip](https://sqlite.org/2025/sqlite-amalgamation-3500400.zip).
The SQLite changelog is here: https://sqlite.org/changes.html (Updated from 3.45.2)
Tested with the latest master branch and Godot 4.5 stable release, no issues.
> SQLite: Update to 3.50.4
