Zylann/godot_voxel

- meshers/dmc/voxel_mesher_dmc.cpp
> Fix gcc build

- README.md
- doc/04_materials.md
Added on docs how to enable AO, as mentioned on #43
fixes #43
> Added info in order to enable AO

- streams/voxel_block_serializer.cpp
- streams/voxel_stream_region_files.cpp
- streams/voxel_stream_region_files.h
- terrain/block_thread_manager.h
- terrain/voxel_block.cpp
- terrain/voxel_data_loader.cpp
- terrain/voxel_data_loader.h
- terrain/voxel_lod_terrain.cpp
- terrain/voxel_mesh_updater.cpp
- terrain/voxel_terrain.cpp
@lordee Can you confirm that this PR fixes the warnings?
Errors already fixed in 1ad71c5.
Fixes #61 
Fixes #67
> Fix mono & gcc build issues

- error_macros.h
- streams/voxel_block_serializer.cpp
- streams/voxel_stream_region_files.cpp
- terrain/voxel_map.cpp
- util/direct_static_body.cpp
Tested on linux/gcc w/ and w/o mono.
Fixes #64
> Allow building against Godot 3.1 branch

- streams/voxel_stream.cpp
> Fix build errors due to Godot macro change

- .gitignore
> gitignore: .bc (html5 builds)

- generators/voxel_generator_test.cpp
- terrain/voxel_terrain.cpp
- util/array_slice.h
- voxel_buffer.cpp
This prevented Godot from compiling with voxel module.
> Added missing semicolons on line endings

- generators/voxel_generator_test.cpp
- meshers/blocky/voxel_mesher_blocky.cpp
- meshers/transvoxel/voxel_mesher_transvoxel.cpp
- streams/voxel_stream_region_files.cpp
- terrain/voxel_lod_terrain.cpp
- terrain/voxel_terrain.cpp
- voxel_buffer.cpp
This can be merged first. Unrelated to the other PR.
The only remaining warnings are two functions declared but not used.
Also gcc hates your ascii art.
> Fix gcc warnings

- doc/01_get-started.md
- doc/05_collision.md
- doc/06_custom-generator.md
Fix some broken links in the docs.
> Fix doc links

- util/voxel_raycast.h
> Added raycast case for integer positions

- doc/classes/VoxelTool.xml
- edition/voxel_tool.cpp
Please review, especially at comments. I'll update after review.
> Implement VoxelTool::do_box(...)

- .github/workflows/fuzzer.yml
- .github/workflows/test_project.yml
- misc/check_ci_log.py
This PR adds CI with opening and closing editor and running test project
Example run - https://github.com/qarmin/godot_voxel/runs/3782638178?check_suite_focus=true
It found a lot of errors like 
```
modules/voxel/generators/graph/voxel_graph_runtime.cpp:443:44: runtime error: load of misaligned address 0x6070006be713 for type 'const short unsigned int', which requires 2 byte alignment
0x6070006be713: note: pointer points here
00  14 01 00 05 00 08 00 00  00 00 00 00 00 80 3f 06  06 00 05 00 07 00 00 00  2a 07 00 08 00 00 00
^ 
modules/voxel/generators/graph/voxel_graph_runtime.cpp:572:58: runtime error: load of misaligned address 0x6070006be72b for type 'const short unsigned int', which requires 2 byte alignment
0x6070006be72b: note: pointer points here
00  2a 07 00 08 00 00 00 2a  05 00 …
```
> Add test CI and fuzzer

- server/voxel_server.cpp
> Fixed clang build

- storage/voxel_buffer.h
- storage/voxel_data_block.h
- streams/vox_data.h
Could not compile as 3 times include <memory> was missing in 3 files for shared_ptr and unique_ptr
> Missing includes

- streams/voxel_stream.h
Included header file for the Dynamic memory management lib to define unique_ptr and shared_ptr.
> missing lib?

- generators/graph/voxel_graph_node_db.cpp
- meshers/blocky/voxel_blocky_model.cpp
- terrain/fixed_lod/voxel_terrain.cpp
- terrain/instancing/voxel_instancer.cpp
- util/godot/funcs.cpp
Just a quick fix for changes to hashmaps in the master godot branch https://github.com/godotengine/godot/commit/8b7c7f5a753b43cec10f72b274bb1d70c253652b
> Fixed issues caused by changes to HashMap in godot

- .github/workflows/test_project.yml
This appears to fix the last branch affected by issue #397 so I made a list there for clarity. I only checked versioned branches and master, but if any other branch is active please comment and I can fix it.
> Account for the renamed test project in the godot3.4 branch (resolves #397).

- streams/sqlite/voxel_stream_sqlite.cpp
- streams/sqlite/voxel_stream_sqlite.h
Also rename the argument to `p_connection`.
> Rename `flush_cache` with connection parameter to `flush_cache_to_connection`

- util/godot/classes/editor_file_dialog.h
- util/godot/classes/editor_spin_slider.h
> fix broken includes

- constants/voxel_string_names.cpp
- constants/voxel_string_names.h
- terrain/fixed_lod/voxel_terrain.cpp
- terrain/fixed_lod/voxel_terrain.h
add 'block_meshed' and 'block_unmeshed' signals to VoxelTerrain.
> add 'block_meshed' and 'block_unmeshed' signals to VoxelTerrain

- edition/mesh_sdf.h
- edition/voxel_tool_lod_terrain.cpp
- engine/generate_block_task.cpp
- engine/voxel_engine.cpp
- engine/voxel_engine.h
- gource_view.sh
- storage/funcs.cpp
- storage/voxel_buffer_internal.cpp
- storage/voxel_buffer_internal.h
- storage/voxel_data.h
- storage/voxel_data_map.cpp
- storage/voxel_data_map.h
- storage/voxel_metadata.h
- streams/region/voxel_stream_region_files.cpp
- streams/sqlite/voxel_stream_sqlite.cpp
- streams/vox/vox_data.cpp
- streams/voxel_block_serializer_gd.cpp
- streams/voxel_stream.h
- terrain/fixed_lod/voxel_terrain.cpp
- terrain/variable_lod/voxel_lod_terrain.cpp
- terrain/variable_lod/voxel_lod_terrain_update_task.cpp
- terrain/voxel_node.cpp
This pull request fixes some typos. No functional changes are intended.
> Fix some typos

- .github/workflows/macos.yml
> Add macOS x86_64 checks

- editor/instance_library/voxel_instance_library_multimesh_item_inspector_plugin.cpp
- terrain/instancing/voxel_instance_library_multimesh_item.cpp
- terrain/instancing/voxel_instance_library_multimesh_item.h
- terrain/instancing/voxel_instancer.cpp
- util/godot/direct_multimesh_instance.cpp
- util/godot/direct_multimesh_instance.h
> Add renering layer for VoxelLibraryMultiMeshItem

- doc/source/specs/block_format_v1.md
- doc/source/specs/block_format_v2.md
- doc/source/specs/block_format_v3.md
- doc/source/specs/block_format_v4.md
- doc/source/specs/compressed_container.md
- doc/source/specs/region_format_v2.md
- doc/source/specs/region_format_v3.md
- streams/compressed_data.cpp
- streams/instance_data.cpp
- streams/region/region_file.cpp
- streams/voxel_block_serializer.cpp
- terrain/fixed_lod/voxel_terrain_multiplayer_synchronizer.cpp
- util/io/serialization.h
> Fix 72 typos in 13 files

- generators/multipass/generate_column_multipass_task.cpp
- meshers/blocky/types/voxel_blocky_type.cpp
- meshers/blocky/types/voxel_blocky_type_library.cpp
- streams/region/region_file.cpp
- streams/vox/vox_data.cpp
Fixes compilation with `warnings=extra werror=yes strict_checks=yes`
> Use `Ref.is_valid``Ref.is_null` and rm a unused variable
